title: Neil's Portfolio
author: Neil D. Fink
email: mrnfink@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my page that houses my life's work. 
  I shall actively throw game examples, code morsels, 
  and many more things onto this site. 
  I thank you for taking the time to get to know me and my work.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
