remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Neil's Morsels
author: Neil D. Fink
email: mrnfink@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my portfolio website. All my games and coding work go here. Thank you very much for stopping by and observing.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
